### PR TITLE
Derive CreatedAt from lvdisplay

### PR DESCRIPTION
**Pull request by shishir-a412ed**

### CODE REVIEW

**Comment by Ashald** [comment]
LGTM! 👍

**Comment by rhatdan** [comment]
LGTM

**Comment by shishir-a412ed** [comment]
@rhatdan `Lets move this to github.com/containers since projectatomic is sort of going away.` 
Sure, how to move it under `github.com/containers`? I don't have admin rights on this repo.

IIRC, @jwhonce created this repo initially.

**Comment by rhatdan** [comment]
Moved and I made you admin.

**Pull request merged**
