### PR TITLE
PART 2: Add support for thinly-provisioned volumes and snapshots

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
@cschauer So I think I got this completed :)
If you have sometime, can you try it out and see if it covers all the use cases.

There is a small Caveat:
Since now there are changes to the in-memory store (which is also persisted on disk). You might have to start with a new environment i.e. no volumes present using lvm driver.
Now if you have this (docker-lvm-plugin) running in production, I can help you update the db file manually with new fields {Type, Source}.

db file is: `/var/lib/docker-lvm-plugin/lvmVolumesConfig.json`

Meanwhile I will try to update the doc and man pages.

Shishir

**Comment by shishir-a412ed** [comment]
@cschauer On second thought (n After discussing it with @rhatdan ) I don't think this should affect lvm volumes created before these features (thin devices and snapshots) were introduced. 

So just try it out, and let me know if you face any issues.

Thanks !
Shishir

**Comment by cschauer** [comment]
@shishir-a412ed Thanks! I'll test it out and report back.

**Comment by shishir-a412ed** [comment]
@cschauer Just checking if you got a chance to look at this.

Shishir

**Comment by shishir-a412ed** [comment]
@cschauer Any updates :)

Shishir

**Comment by shishir-a412ed** [comment]
LGTM. Merging.

**Pull request merged**
