### PR TITLE
Fix import path for ProcessExitCode().

### PR DESCRIPTION
**Pull request by amatsus**
This is related to https://github.com/docker/docker/commit/d7022f2b46589cb9d860219e1d8278351ba147c3.

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
@amatsus Thanks !
LGTM.

**Comment by shishir-a412ed** [comment]
@lsm5 Can we build a new rpm for `docker-lvm-plugin` with these changes ?

/cc @rhatdan

**Comment by amatsus** [comment]
@shishir-a412ed Thanks, merged :) I'd say it's early to build a new rpm because this commit is needed to build with https://github.com/projectatomic/docker/tree/docker-1.13. Would you like to create a new branch for docker-1.12 or earlier.

**Comment by shishir-a412ed** [comment]
@amatsus yeah discussed it with @lsm5. Have dropped (building the new rpm) it for now.

Shishir

**Pull request merged**
