### PR TITLE
Fix issue: Auto-mount not working after server crash

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Fixes Issue #24 

Signed-off-by: Shishir Mahajan <shishirm@nvidia.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
@rhatdan Please review.

**Comment by rhatdan** [comment]
Not quite sure what you are doing, but the code LGTM

**Comment by shishir-a412ed** [comment]
@rhatdan

In case of reboot, systemd unmount the volumes. So during reboot, when the containers exit, they call the unmount path of the plugin and when the plugin tries to unmount the volume it fails (Since the volume is already unmounted by systemd)

With this PR:
The plugin will first check if the directory is a mountpoint. If yes, only then it will try to unmount.

**Comment by shishir-a412ed** [comment]
@rhatdan

More explanation here:
https://github.com/projectatomic/docker-lvm-plugin/issues/24#issuecomment-399784514

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
