### PR TITLE
log error messages to syslog to ease debugging

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
ping @runcom @rhatdan

**Comment by runcom** [comment]
fine to me, eventually we should send those logs to journald instead of stderr

**Comment by shishir-a412ed** [comment]
@runcom 
I checked these error messages using `journalctl`, and I was able to see them. 
E.g if I run `docker volume create -d lvm --name foobar --opt size=2G` where my volume_group size is 1G I can see an error message logged in my journalctl.

When I do` journalctl -u docker-lvm-plugin -f`. I see my messages.

Anything else I need to take care of ?

Shishir

**Comment by rhatdan** [comment]
Those messages are coming from the docker-lvm-plugin.service unit file versus coming from the docker-lvm-plugin executable.  Probably would be better to write to syslog handle it that way.

**Comment by shishir-a412ed** [comment]
@rhatdan So after logging to `syslog`, Can I still use `journalctl` to check my errors ?

Shishir

**Comment by rhatdan** [comment]
Yes journalctl catches all syslog messages.

**Comment by shishir-a412ed** [comment]
@rhatdan @runcom PTAL.

Shishir

**Comment by rhatdan** [comment]
Looks good, should we have logs.Info to tell when the tool does major changes to lvm?

**Comment by shishir-a412ed** [comment]
Sure I can add one. Merging this one. LGTM.

**Pull request merged**
